# compose.yaml
services:
  endon-db:
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "${DOCKER_INFLUXDB_HOST}/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - traefik
      - default

  endon-ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.endon-ingestor.rule=Host(`${PROXY_URL}`)
      - traefik.http.routers.endon-ingestor.tls=true
      - traefik.http.routers.endon-ingestor.tls.certresolver=letsencrypt
      - traefik.http.services.endon-ingestor.loadbalancer.server.port=80
    depends_on:
      endon-db:
        condition: service_healthy
    networks:
      - traefik
      - default
    env_file:
      - .env
      
volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  traefik:
    external: true