services:
  endon-ingestor:
    environment:
      - DEBUG=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.endon-ingestor.rule=Host(`localhost`)
      - traefik.http.routers.endon-ingestor.tls=false
      - traefik.http.routers.endon-ingestor.tls.certresolver=
      - traefik.http.services.endon-ingestor.loadbalancer.server.port=80
  traefik:
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml
